---
- hosts: all
  gather_facts: true
  connection: local
  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output
    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "/etc/ansible/backup/{{inventory_hostname}}.config"
